# Generated by Django 2.0.6 on 2018-06-27 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20180627_0630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='link_posts',
            new_name='like_posts',
        ),
    ]
